spring:
  datasource:
    url: jdbc:h2:mem:boarddb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
  profiles:
    active: dev
