spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boarddb
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
  profiles:
    active: prod
